# Generated by Django 5.1.1 on 2025-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_enrollment_dob_alter_gallery_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.CharField(max_length=55),
        ),
    ]
