# Generated by Django 5.1.1 on 2025-01-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
