# Generated by Django 5.1.1 on 2025-01-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_enrollment_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
